// nextjs/src/app/(dashboard)/tasks/page.tsx
import { prisma } from '@/lib/db'
import { formatDate } from '@/lib/utils'

import { Badge } from '@/components/ui/badge'
import Link from 'next/link'

const columns = [
  { key: 'TODO', label: 'Att göra', color: 'bg-gray-100 text-gray-700' },
  { key: 'IN_PROGRESS', label: 'Pågående', color: 'bg-[#dbeafe] text-[#1d4ed8]' },
  { key: 'REVIEW', label: 'Granskning', color: 'bg-yellow-100 text-yellow-700' },
  { key: 'DONE', label: 'Klart', color: 'bg-green-100 text-green-700' },
]

const priorityVariant: Record<string, 'gray' | 'info' | 'warning' | 'danger'> = {
  LOW: 'gray',
  MEDIUM: 'info',
  HIGH: 'warning',
  URGENT: 'danger',
}

const priorityLabel: Record<string, string> = {
  LOW: 'Låg',
  MEDIUM: 'Medium',
  HIGH: 'Hög',
  URGENT: 'Brådskande',
}

export default async function UppgifterPage() {
  const tasks = await prisma.task.findMany({
    where: { status: { not: 'CANCELLED' } },
    include: { assignee: true, customer: true, project: true },
    orderBy: { createdAt: 'desc' },
  })

  const byStatus: Record<string, typeof tasks> = {}
  for (const col of columns) {
    byStatus[col.key] = tasks.filter((t) => t.status === col.key)
  }

  return (
    <div className="space-y-6">
      <div className="page-hero pb-5 flex items-start justify-between gap-4">
        <div>
          <p className="page-kicker">Arbete</p>
          <h1 className="text-2xl font-bold text-gray-900 mt-0.5">Uppgifter</h1>
          <p className="text-sm text-gray-500 mt-0.5">{tasks.length} uppgifter totalt</p>
        </div>
      </div>

      {/* Kanban */}
      <div className="flex gap-4 overflow-x-auto pb-4">
        {columns.map((col) => (
          <div key={col.key} className="flex-shrink-0 w-72">
            <div className="flex items-center gap-2 mb-3">
              <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium ${col.color}`}>
                {col.label}
              </span>
              <span className="text-xs text-gray-400 ml-auto">{byStatus[col.key]?.length ?? 0}</span>
            </div>

            <div className="space-y-3">
              {(byStatus[col.key]?.length ?? 0) === 0 ? (
                <div className="rounded-lg border-2 border-dashed border-gray-200 p-4 text-center text-xs text-gray-400">
                  Inga uppgifter
                </div>
              ) : (
                byStatus[col.key].map((task) => (
                  <div key={task.id} className="panel-surface p-4">
                    <div className="flex items-start justify-between gap-2">
                      <h3 className="font-medium text-gray-900 text-sm leading-snug">{task.title}</h3>
                      <Badge variant={priorityVariant[task.priority] ?? 'gray'}>
                        {priorityLabel[task.priority] ?? task.priority}
                      </Badge>
                    </div>
                    {(task.customer || task.project) && (
                      <div className="flex flex-wrap gap-1.5 mt-2">
                        {task.customer && (
                          <Link
                            href={`/customers/${task.customer.id}`}
                            className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 bg-blue-50 text-blue-700 rounded hover:bg-blue-100 transition-colors dark:bg-blue-950/30 dark:text-blue-400"
                          >
                            {task.customer.name}
                          </Link>
                        )}
                        {task.project && (
                          <Link
                            href={`/projects/${task.project.id}`}
                            className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 bg-cyan-50 text-cyan-700 rounded hover:bg-cyan-100 transition-colors dark:bg-cyan-950/30 dark:text-cyan-400"
                          >
                            {task.project.name}
                          </Link>
                        )}
                      </div>
                    )}
                    <div className="flex items-center justify-between mt-2">
                      {task.dueDate ? (
                        <span className="text-xs text-gray-500">
                          Förfaller {formatDate(task.dueDate)}
                        </span>
                      ) : (
                        <span />
                      )}
                      {task.assignee && (
                        <div className="h-6 w-6 rounded-full bg-zinc-100 flex items-center justify-center">
                          <span className="text-xs font-semibold text-zinc-700">
                            {task.assignee.name.charAt(0)}
                          </span>
                        </div>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// svelte/src/routes/(dashboard)/dashboard/tasks/+page.svelte
<script lang="ts">
	import Card from "$lib/components/ui/card.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import { PlusIcon } from "heroicons-svelte/24/outline";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();

	const statuses = [
		{ id: "TODO", label: "Att göra", color: "bg-gray-100" },
		{ id: "IN_PROGRESS", label: "Pågår", color: "bg-blue-100" },
		{ id: "REVIEW", label: "Granskning", color: "bg-yellow-100" },
		{ id: "DONE", label: "Klar", color: "bg-green-100" },
	];

	function getTasksByStatus(status: string) {
		return data.tasks.filter((t) => t.status === status);
	}
</script>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-3xl font-bold text-gray-900">Uppgifter</h1>
			<p class="mt-2 text-gray-600">Hantera dina uppgifter och projekt</p>
		</div>
		<a href="/dashboard/tasks/new">
			<Button>
				<PlusIcon class="mr-2 h-5 w-5" />
				Ny uppgift
			</Button>
		</a>
	</div>

	<!-- Filter -->
	<div class="flex flex-wrap items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 p-3">
		<span class="text-sm text-gray-600">Filtrera:</span>
		<a href="/dashboard/tasks" class="rounded border border-gray-300 bg-white px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-50">Alla</a>
		{#each data.projects as p}
			<a href="/dashboard/tasks?projectId={p.id}" class="rounded border border-gray-300 bg-white px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-50">{p.name}</a>
		{/each}
		<span class="ml-2 text-sm text-gray-500">|</span>
		{#each data.users as u}
			<a href="/dashboard/tasks?assignedTo={u.id}" class="rounded border border-gray-300 bg-white px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-50">{u.name}</a>
		{/each}
		<span class="ml-2 text-sm text-gray-500">|</span>
		{#each statuses as s}
			<a href="/dashboard/tasks?status={s.id}" class="rounded border border-gray-300 bg-white px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-50">{s.label}</a>
		{/each}
	</div>
	
	<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
		{#each statuses as status}
			<div class="space-y-3">
				<div class="flex items-center justify-between">
					<h2 class="font-semibold text-gray-900">{status.label}</h2>
					<span class="rounded-full bg-gray-200 px-2 py-1 text-xs font-medium text-gray-700">
						{getTasksByStatus(status.id).length}
					</span>
				</div>
				<div class="space-y-3">
					{#each getTasksByStatus(status.id) as task}
						<Card class="p-4 hover:shadow-md transition-shadow cursor-pointer">
							<a href="/dashboard/tasks/{task.id}" class="block">
								<h3 class="font-medium text-gray-900">{task.title}</h3>
								{#if task.description}
									<p class="mt-1 text-sm text-gray-600 line-clamp-2">{task.description}</p>
								{/if}
								<div class="mt-3 flex items-center justify-between text-xs text-gray-500">
									{#if task.assignee}
										<span>{task.assignee.name}</span>
									{:else}
										<span class="text-gray-400">Ej tilldelad</span>
									{/if}
									{#if task.dueDate}
										<span>{new Date(task.dueDate).toLocaleDateString()}</span>
									{/if}
								</div>
							</a>
						</Card>
					{/each}
					{#if getTasksByStatus(status.id).length === 0}
						<Card class="p-8 text-center text-sm text-gray-500">
							Inga uppgifter
						</Card>
					{/if}
				</div>
			</div>
		{/each}
	</div>
</div>
