// svelte/src/routes/(dashboard)/dashboard/contacts/+page.svelte
<script lang="ts">
	import Card from "$lib/components/ui/card.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import Input from "$lib/components/ui/input.svelte";
	import { MagnifyingGlassIcon, PlusIcon } from "heroicons-svelte/24/outline";
	import type { PageData } from "./$types";
	
	let { data }: { data: PageData } = $props();

	let searchQuery = $state("");
	let selectedCompany = $state("");
	$effect(() => {
		searchQuery = data.search ?? "";
		selectedCompany = data.companyId ?? "";
	});
	
	const filteredContacts = $derived(
		data.contacts.filter((c) => {
			const matchesSearch = !searchQuery || 
				`${c.firstName} ${c.lastName}`.toLowerCase().includes(searchQuery.toLowerCase()) ||
				c.email?.toLowerCase().includes(searchQuery.toLowerCase());
			const matchesCompany = !selectedCompany || c.companyId === selectedCompany;
			return matchesSearch && matchesCompany;
		})
	);
</script>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-3xl font-bold text-gray-900">Kontakter</h1>
			<p class="mt-2 text-gray-600">Hantera din kontaktdatabas</p>
		</div>
		<a href="/dashboard/contacts/new">
			<Button>
				<PlusIcon class="mr-2 h-5 w-5" />
				Lägg till kontakt
			</Button>
		</a>
	</div>
	
	<div class="flex gap-4">
		<div class="relative flex-1 max-w-md">
			<MagnifyingGlassIcon class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />
			<Input
				type="text"
				placeholder="Sök kontakter..."
				bind:value={searchQuery}
				class="pl-10"
			/>
		</div>
		<select
			bind:value={selectedCompany}
			class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
		>
			<option value="">Alla företag</option>
			{#each data.companies as company}
				<option value={company.id}>{company.name}</option>
			{/each}
		</select>
	</div>
	
	{#if filteredContacts.length === 0}
		<Card class="p-12 text-center">
			<p class="text-gray-500">Inga kontakter hittades</p>
			<a href="/dashboard/contacts/new" class="mt-4 inline-block text-blue-600 hover:text-blue-700">
				Lägg till din första kontakt
			</a>
		</Card>
	{:else}
		<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
			{#each filteredContacts as contact}
				<Card class="p-6 hover:shadow-md transition-shadow">
					<a href="/dashboard/contacts/{contact.id}" class="block">
						<h3 class="text-lg font-semibold text-gray-900 hover:text-blue-600">
							{contact.firstName} {contact.lastName}
						</h3>
						{#if contact.title}
							<p class="mt-1 text-sm text-gray-600">{contact.title}</p>
						{/if}
						<p class="mt-2 text-sm text-gray-500">{contact.company.name}</p>
						{#if contact.email}
							<p class="mt-1 text-sm text-gray-600">{contact.email}</p>
						{/if}
					</a>
				</Card>
			{/each}
		</div>
	{/if}
</div>

// nextjs/src/app/(dashboard)/contacts/page.tsx
import { prisma } from '@/lib/db'
import { formatDate } from '@/lib/utils'

import Link from 'next/link'

interface PageProps {
  searchParams: Promise<{ q?: string }>
}

export default async function KontakterPage({ searchParams }: PageProps) {
  const { q } = await searchParams

  const contacts = await prisma.contact.findMany({
    where: q
      ? {
          OR: [
            { firstName: { contains: q } },
            { lastName: { contains: q } },
            { email: { contains: q } },
          ],
        }
      : {},
    include: { customer: true },
    orderBy: [{ firstName: 'asc' }, { lastName: 'asc' }],
  })

  return (
    <div className="space-y-6">
      <div className="page-hero pb-5 flex items-start justify-between gap-4">
        <div>
          <p className="page-kicker">CRM</p>
          <h1 className="text-2xl font-bold text-gray-900 mt-0.5">Kontakter</h1>
          <p className="text-sm text-gray-500 mt-0.5">{contacts.length} kontakter totalt</p>
        </div>
      </div>

      {/* Search */}
      <form method="GET">
        <input
          name="q"
          defaultValue={q}
          placeholder="Sök kontakt, e-post..."
          className="flex h-10 w-full max-w-sm rounded-lg border border-gray-200 bg-gray-50/50 px-3 py-2 text-sm text-gray-900 placeholder:text-gray-400 focus:border-zinc-500 focus:outline-none focus:ring-2 focus:ring-zinc-500/20 focus:bg-white transition-all"
        />
      </form>

      <div className="panel-surface">
          {contacts.length === 0 ? (
            <div className="p-10 text-center text-gray-400 text-sm">Inga kontakter hittades</div>
          ) : (
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50/50">
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Namn</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Företag</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Titel</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">E-post</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Telefon</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Skapad</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {contacts.map((contact) => (
                  <tr key={contact.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4">
                      <Link
                        href={`/contacts/${contact.id}`}
                        className="font-medium text-gray-900 hover:text-zinc-600 transition-colors"
                      >
                        {contact.firstName} {contact.lastName}
                      </Link>
                    </td>
                    <td className="px-6 py-4 text-gray-600">
                      <Link
                        href={`/customers/${contact.customerId}`}
                        className="hover:underline text-gray-700"
                      >
                        {contact.customer.name}
                      </Link>
                    </td>
                    <td className="px-6 py-4 text-gray-600">{contact.title ?? '–'}</td>
                    <td className="px-6 py-4 text-gray-600">{contact.email ?? '–'}</td>
                    <td className="px-6 py-4 text-gray-600">{contact.phone ?? '–'}</td>
                    <td className="px-6 py-4 text-gray-500">{formatDate(contact.createdAt)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
      </div>
    </div>
  )
}
