// nextjs/src/app/(dashboard)/customers/new/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { toast } from '@/lib/toast'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'

function FieldLabel({ children, required }: { children: React.ReactNode; required?: boolean }) {
  return (
    <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">
      {children}{required && <span className="ml-1 text-red-400 normal-case tracking-normal">*</span>}
    </label>
  )
}

export default function NyKundPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setLoading(true)

    const form = e.currentTarget
    const data = Object.fromEntries(new FormData(form))

    try {
      const res = await fetch('/api/customers', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      })
      if (!res.ok) throw new Error()
      toast.success('Kund skapad!')
      router.push('/customers')
    } catch {
      toast.error('Kunde inte skapa kunden. Försök igen.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Breadcrumb + header */}
      <div>
        <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-3">
          <Link href="/customers" className="hover:text-gray-600 transition-colors">Kunder</Link>
          <ChevronRight className="h-3 w-3" />
          <span className="text-gray-600">Ny kund</span>
        </div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-zinc-100">Ny kund</h1>
        <p className="text-sm text-gray-500 mt-0.5">Fyll i företagsinformationen nedan</p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-5">
        {/* Grunduppgifter */}
        <div className="panel-surface">
          <div className="px-6 py-4 border-b border-gray-100 dark:border-zinc-800">
            <h2 className="text-sm font-semibold text-gray-900 dark:text-white">Företagsinformation</h2>
          </div>
          <div className="p-6 space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <FieldLabel required>Företagsnamn</FieldLabel>
                <Input name="name" required placeholder="Exempelbolaget AB" />
              </div>
              <div>
                <FieldLabel>Organisationsnummer</FieldLabel>
                <Input name="orgNumber" placeholder="XXXXXX-XXXX" />
              </div>
              <div>
                <FieldLabel>Bransch</FieldLabel>
                <Input name="industry" placeholder="T.ex. IT, Bygg, Handel" />
              </div>
              <div>
                <FieldLabel>Webbplats</FieldLabel>
                <Input name="website" placeholder="https://exempel.se" />
              </div>
              <div>
                <FieldLabel>Telefon</FieldLabel>
                <Input name="phone" placeholder="08-123 456 78" />
              </div>
              <div>
                <FieldLabel>E-post</FieldLabel>
                <Input name="email" type="email" placeholder="info@exempel.se" />
              </div>
            </div>
          </div>
        </div>

        {/* Adress */}
        <div className="panel-surface">
          <div className="px-6 py-4 border-b border-gray-100 dark:border-zinc-800">
            <h2 className="text-sm font-semibold text-gray-900 dark:text-white">Adress</h2>
          </div>
          <div className="p-6 space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <FieldLabel>Gatuadress</FieldLabel>
                <Input name="address" placeholder="Storgatan 1" />
              </div>
              <div>
                <FieldLabel>Stad</FieldLabel>
                <Input name="city" placeholder="Stockholm" />
              </div>
              <div>
                <FieldLabel>Postnummer</FieldLabel>
                <Input name="zip" placeholder="123 45" />
              </div>
              <div className="col-span-2">
                <FieldLabel>Land</FieldLabel>
                <Input name="country" defaultValue="Sverige" />
              </div>
            </div>
          </div>
        </div>

        {/* Anteckningar */}
        <div className="panel-surface">
          <div className="px-6 py-4 border-b border-gray-100 dark:border-zinc-800">
            <h2 className="text-sm font-semibold text-gray-900 dark:text-white">Anteckningar</h2>
          </div>
          <div className="p-6">
            <Textarea name="notes" placeholder="Övrig information om kunden…" rows={4} />
          </div>
        </div>

        <div className="flex items-center gap-3 pt-1">
          <Button type="submit" disabled={loading}>
            {loading ? 'Sparar…' : 'Skapa kund'}
          </Button>
          <Button type="button" variant="outline" onClick={() => router.push('/customers')}>
            Avbryt
          </Button>
        </div>
      </form>
    </div>
  )
}

// svelte/src/routes/(dashboard)/dashboard/customers/new/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { goto } from "$app/navigation";
	import Card from "$lib/components/ui/card.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import Input from "$lib/components/ui/input.svelte";
	import Label from "$lib/components/ui/label.svelte";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();

	let loading = $state(false);
	let error = $state("");

	let formData = $state({
		name: "",
		email: "",
		phone: "",
		industry: "",
		website: "",
	});
</script>

<div class="max-w-2xl space-y-6">
	<div>
		<h1 class="text-3xl font-bold text-gray-900">Lägg till kund</h1>
		<p class="mt-2 text-gray-600">Skapa ett nytt kundföretag</p>
	</div>

	<Card class="p-6">
		{#if error}
			<div class="mb-4 rounded-md bg-red-50 p-4">
				<p class="text-sm text-red-800">{error}</p>
			</div>
		{/if}

		<form
			method="POST"
			action="?/create"
			use:enhance={() => {
				loading = true;
				return async ({ result, update }) => {
					await update();
					loading = false;
					if (result.type === "redirect") {
						goto(result.location);
					} else if (result.type === "failure") {
						error = result.data?.error ?? "Kunde inte skapa kund";
					}
				};
			}}
		>
			<div class="space-y-4">
				<div>
					<Label for="name">Företagsnamn *</Label>
					<Input id="name" name="name" bind:value={formData.name} required placeholder="Acme AB" />
				</div>

				<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
					<div>
						<Label for="email">E-post</Label>
						<Input id="email" name="email" type="email" bind:value={formData.email} placeholder="kontakt@acme.se" />
					</div>
					<div>
						<Label for="phone">Telefon</Label>
						<Input id="phone" name="phone" bind:value={formData.phone} placeholder="+46 8 123 456 78" />
					</div>
				</div>

				<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
					<div>
						<Label for="industry">Bransch</Label>
						<Input id="industry" name="industry" bind:value={formData.industry} placeholder="Teknik" />
					</div>
					<div>
						<Label for="website">Webbplats</Label>
						<Input id="website" name="website" bind:value={formData.website} placeholder="https://acme.se" />
					</div>
				</div>

				<div class="flex gap-4 pt-4">
					<Button type="submit" disabled={loading}>
						{loading ? "Skapar..." : "Skapa kund"}
					</Button>
					<a href="/dashboard/customers">
						<Button variant="outline" type="button">Avbryt</Button>
					</a>
				</div>
			</div>
		</form>
	</Card>
</div>
