// nextjs/src/app/(dashboard)/quotes/page.tsx
import { prisma } from '@/lib/db'
import { formatDate, formatCurrency } from '@/lib/utils'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

interface PageProps {
  searchParams: Promise<{ status?: string }>
}

const statusLabel: Record<string, string> = {
  DRAFT: 'Utkast',
  SENT: 'Skickad',
  ACCEPTED: 'Accepterad',
  REJECTED: 'Avvisad',
  EXPIRED: 'Utgången',
}

const statusVariant: Record<string, 'gray' | 'info' | 'success' | 'danger' | 'warning'> = {
  DRAFT: 'gray',
  SENT: 'info',
  ACCEPTED: 'success',
  REJECTED: 'danger',
  EXPIRED: 'warning',
}

export default async function OfferterPage({ searchParams }: PageProps) {
  const { status } = await searchParams

  const quotes = await prisma.quote.findMany({
    where: status ? { status: status as never } : {},
    include: { customer: true },
    orderBy: { createdAt: 'desc' },
  })

  const statusOptions = ['DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED']

  return (
    <div className="space-y-6">
      <div className="page-hero pb-5 flex items-start justify-between gap-4">
        <div>
          <p className="page-kicker">Affär</p>
          <h1 className="text-2xl font-bold text-gray-900 mt-0.5">Offerter</h1>
          <p className="text-sm text-gray-500 mt-0.5">{quotes.length} offerter</p>
        </div>
        <Link href="/quotes/new">
          <Button>+ Ny offert</Button>
        </Link>
      </div>

      {/* Filter */}
      <div className="flex gap-2 flex-wrap">
        <Link
          href="/quotes"
          className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
            !status ? 'bg-zinc-800 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
          }`}
        >
          Alla
        </Link>
        {statusOptions.map((s) => (
          <Link
            key={s}
            href={`/quotes?status=${s}`}
            className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
              status === s
                ? 'bg-zinc-800 text-white'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
          >
            {statusLabel[s]}
          </Link>
        ))}
      </div>

      <div className="panel-surface">
          {quotes.length === 0 ? (
            <div className="p-10 text-center text-gray-400 text-sm">Inga offerter hittades</div>
          ) : (
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50/50">
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Nummer</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Titel</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Kund</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Totalt</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Giltig till</th>
                  <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">Datum</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {quotes.map((quote) => (
                  <tr key={quote.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4">
                      <Link
                        href={`/quotes/${quote.id}`}
                        className="font-medium text-gray-900 hover:text-zinc-600 transition-colors"
                      >
                        {quote.number}
                      </Link>
                    </td>
                    <td className="px-6 py-4 text-gray-900">{quote.title}</td>
                    <td className="px-6 py-4 text-gray-600">{quote.customer.name}</td>
                    <td className="px-6 py-4">
                      <Badge variant={statusVariant[quote.status] ?? 'gray'}>
                        {statusLabel[quote.status] ?? quote.status}
                      </Badge>
                    </td>
                    <td className="px-6 py-4 text-gray-900 font-medium">{formatCurrency(quote.total)}</td>
                    <td className="px-6 py-4 text-gray-500">{formatDate(quote.validUntil)}</td>
                    <td className="px-6 py-4 text-gray-500">{formatDate(quote.createdAt)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
      </div>
    </div>
  )
}

// svelte/src/routes/(dashboard)/dashboard/quotes/+page.svelte
<script lang="ts">
	import Card from "$lib/components/ui/card.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import { PlusIcon } from "heroicons-svelte/24/outline";
	import { format } from "date-fns";
	import { sv } from "date-fns/locale";
	import type { PageData } from "./$types";
	
	let { data }: { data: PageData } = $props();
	
	const statusColors = {
		DRAFT: "bg-gray-100 text-gray-800",
		SENT: "bg-blue-100 text-blue-800",
		ACCEPTED: "bg-green-100 text-green-800",
		REJECTED: "bg-red-100 text-red-800",
		EXPIRED: "bg-yellow-100 text-yellow-800",
	};
	const statusLabels: Record<string, string> = {
		DRAFT: "Utkast",
		SENT: "Skickad",
		ACCEPTED: "Accepterad",
		REJECTED: "Avslagen",
		EXPIRED: "Utgången",
	};
</script>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-3xl font-bold text-gray-900">Offerter</h1>
			<p class="mt-2 text-gray-600">Hantera försäljningsofferter</p>
		</div>
		<a href="/dashboard/quotes/new">
			<Button>
				<PlusIcon class="mr-2 h-5 w-5" />
				Ny offert
			</Button>
		</a>
	</div>
	
	{#if data.quotes.length === 0}
		<Card class="p-12 text-center">
			<p class="text-gray-500">Inga offerter hittades</p>
			<a href="/dashboard/quotes/new" class="mt-4 inline-block text-blue-600 hover:text-blue-700">
				Skapa din första offert
			</a>
		</Card>
	{:else}
		<div class="overflow-x-auto">
			<table class="min-w-full divide-y divide-gray-200">
				<thead class="bg-gray-50">
					<tr>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Offert nr</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Företag</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Titel</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Totalt</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Status</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Skapad</th>
					</tr>
				</thead>
				<tbody class="divide-y divide-gray-200 bg-white">
					{#each data.quotes as quote}
						<tr class="hover:bg-gray-50">
							<td class="whitespace-nowrap px-6 py-4 text-sm font-medium text-gray-900">
								<a href="/dashboard/quotes/{quote.id}" class="text-blue-600 hover:text-blue-700">
									{quote.number}
								</a>
							</td>
							<td class="whitespace-nowrap px-6 py-4 text-sm text-gray-900">{quote.company.name}</td>
							<td class="px-6 py-4 text-sm text-gray-900">{quote.title}</td>
							<td class="whitespace-nowrap px-6 py-4 text-sm text-gray-900">{quote.total.toFixed(2)} kr</td>
							<td class="whitespace-nowrap px-6 py-4">
								<span class="inline-flex rounded-full px-2 py-1 text-xs font-semibold {statusColors[quote.status]}">
									{statusLabels[quote.status] ?? quote.status}
								</span>
							</td>
							<td class="whitespace-nowrap px-6 py-4 text-sm text-gray-500">
								{format(new Date(quote.createdAt), "d MMM yyyy", { locale: sv })}
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</div>
