// nextjs/src/app/login/page.tsx
'use client'

import { useState } from 'react'
import { signIn } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { PasswordInput } from '@/components/ui/password-input'

export default function LoginPage() {
  const router = useRouter()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setError('')

    const res = await signIn('credentials', {
      email,
      password,
      redirect: false,
    })

    setLoading(false)
    if (res?.error) {
      setError('Fel e-post eller lösenord')
    } else {
      router.push('/dashboard')
      router.refresh()
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#fafafa] px-4">
      <div className="w-full max-w-sm">
        <div className="panel-surface overflow-hidden">
          {/* Brand header */}
          <div className="border-b border-gray-100 px-6 py-5">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-zinc-900 text-white">
                <span className="text-sm font-bold">P</span>
              </div>
              <div>
                <h1 className="text-sm font-semibold text-gray-900">
                  Pro<span className="text-zinc-500">SC</span>
                </h1>
                <p className="text-xs text-gray-500">Logga in för att fortsätta</p>
              </div>
            </div>
          </div>

          <div className="p-6">
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 mb-1.5">
                  E-post
                </label>
                <Input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="admin@prosc.com"
                  required
                  autoFocus
                />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 mb-1.5">
                  Lösenord
                </label>
                <PasswordInput
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  required
                />
              </div>

              {error && (
                <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-md px-3 py-2">
                  {error}
                </p>
              )}

              <Button type="submit" className="w-full" size="lg" disabled={loading}>
                {loading ? 'Loggar in…' : 'Logga in'}
              </Button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}

// svelte/src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import Button from "$lib/components/ui/button.svelte";
	import Input from "$lib/components/ui/input.svelte";
	import Label from "$lib/components/ui/label.svelte";
	import Card from "$lib/components/ui/card.svelte";
	
	let email = $state("");
	let password = $state("");
	let error = $state("");
	let loading = $state(false);
</script>

<div class="flex min-h-screen items-center justify-center bg-gray-50 px-4 py-12 sm:px-6 lg:px-8">
	<Card class="w-full max-w-md p-8">
		<div class="mb-8 text-center">
			<h1 class="text-3xl font-bold text-gray-900">ProSC</h1>
			<p class="mt-2 text-sm text-gray-600">Logga in på ditt konto</p>
		</div>
		
		{#if error}
			<div class="mb-4 rounded-md bg-red-50 p-4">
				<p class="text-sm text-red-800">{error}</p>
			</div>
		{/if}
		
		<form
			method="POST"
			action="?/login"
			use:enhance={() => {
				loading = true;
				error = "";
				return async ({ result, update }) => {
					await update();
					loading = false;
					if (result.type === "failure") {
						error = result.data?.error ?? "Något gick fel";
					}
				};
			}}
		>
			<div class="space-y-4">
				<div>
					<Label for="email">E-post</Label>
					<Input
						id="email"
						name="email"
						type="email"
						bind:value={email}
						required
						placeholder="du@exempel.se"
					/>
				</div>
				
				<div>
					<Label for="password">Lösenord</Label>
					<Input
						id="password"
						name="password"
						type="password"
						bind:value={password}
						required
					/>
				</div>
				
				<Button type="submit" class="w-full" disabled={loading}>
					{loading ? "Loggar in..." : "Logga in"}
				</Button>
			</div>
		</form>
	</Card>
</div>
