// svelte/src/routes/(dashboard)/dashboard/prospects/new/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { goto } from "$app/navigation";
	import Card from "$lib/components/ui/card.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import Input from "$lib/components/ui/input.svelte";
	import Label from "$lib/components/ui/label.svelte";
	import { stageNameSv } from "$lib/i18n/prospectStages";
	import type { PageData } from "./$types";
	
	let { data }: { data: PageData } = $props();
	
	let loading = $state(false);
	let error = $state("");
	
	let formData = $state({
		name: "",
		email: "",
		phone: "",
		industry: "",
		website: "",
		stageId: "",
	});
	$effect(() => {
		formData.stageId = data.stages[0]?.id ?? "";
	});
</script>

<div class="max-w-2xl space-y-6">
	<div>
		<h1 class="text-3xl font-bold text-gray-900">Lägg till nytt prospekt</h1>
		<p class="mt-2 text-gray-600">Skapa ett nytt prospekt i din pipeline</p>
	</div>
	
	<Card class="p-6">
		{#if error}
			<div class="mb-4 rounded-md bg-red-50 p-4">
				<p class="text-sm text-red-800">{error}</p>
			</div>
		{/if}
		
		<form
			method="POST"
			action="?/create"
			use:enhance={() => {
				loading = true;
				return async ({ result, update }) => {
					await update();
					loading = false;
					if (result.type === "redirect") {
						goto(result.location);
					} else if (result.type === "failure") {
						error = result.data?.error || "Kunde inte skapa prospekt";
					}
				};
			}}
		>
			<div class="space-y-4">
				<div>
					<Label for="name">Företagsnamn *</Label>
					<Input
						id="name"
						name="name"
						bind:value={formData.name}
						required
						placeholder="Acme AB"
					/>
				</div>
				
				<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
					<div>
						<Label for="email">E-post</Label>
						<Input
							id="email"
							name="email"
							type="email"
							bind:value={formData.email}
							placeholder="kontakt@acme.se"
						/>
					</div>
					
					<div>
						<Label for="phone">Telefon</Label>
						<Input
							id="phone"
							name="phone"
							bind:value={formData.phone}
							placeholder="+46 8 123 456 78"
						/>
					</div>
				</div>
				
				<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
					<div>
						<Label for="industry">Bransch</Label>
						<Input
							id="industry"
							name="industry"
							bind:value={formData.industry}
							placeholder="Teknik"
						/>
					</div>
					
					<div>
						<Label for="website">Webbplats</Label>
						<Input
							id="website"
							name="website"
							bind:value={formData.website}
							placeholder="https://acme.se"
						/>
					</div>
				</div>
				
				<div>
					<Label for="stageId">Startsteg</Label>
					<select
						id="stageId"
						name="stageId"
						bind:value={formData.stageId}
						class="mt-1 block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
					>
						{#each data.stages as stage}
							<option value={stage.id}>{stageNameSv(stage.name)}</option>
						{/each}
					</select>
				</div>
				
				<div class="flex gap-4 pt-4">
					<Button type="submit" disabled={loading}>
						{loading ? "Skapar..." : "Skapa prospekt"}
					</Button>
					<a href="/dashboard/prospects">
						<Button variant="outline" type="button">Avbryt</Button>
					</a>
				</div>
			</div>
		</form>
	</Card>
</div>

// nextjs/src/app/(dashboard)/prospects/new/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import { toast } from '@/lib/toast'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'

export default function NyttProspektPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setLoading(true)

    const form = e.currentTarget
    const data = Object.fromEntries(new FormData(form))

    try {
      const res = await fetch('/api/prospects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      })

      if (!res.ok) throw new Error()
      toast.success('Prospekt skapat')
      router.push('/prospects')
    } catch {
      toast.error('Ett fel uppstod. Försök igen.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <nav className="flex items-center gap-1.5 text-xs text-gray-400 mb-2">
          <Link href="/prospects" className="hover:text-gray-600 transition-colors">Prospekts</Link>
          <ChevronRight className="h-3 w-3" />
          <span className="text-gray-600">Ny prospekt</span>
        </nav>
        <h1 className="text-2xl font-bold text-gray-900">Nytt prospekt</h1>
        <p className="text-sm text-gray-500 mt-1">Fyll i uppgifterna nedan</p>
      </div>

      <div className="panel-surface">
        <div className="px-6 py-4 border-b border-gray-100 dark:border-zinc-800">
          <h2 className="text-sm font-semibold text-gray-900 dark:text-white">Prospektuppgifter</h2>
        </div>
        <div className="p-6 space-y-4">
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">
                  Företagsnamn <span className="text-red-500">*</span>
                </label>
                <Input name="name" required placeholder="Exempelbolaget AB" />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Organisationsnummer</label>
                <Input name="orgNumber" placeholder="XXXXXX-XXXX" />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Bransch</label>
                <Input name="industry" placeholder="T.ex. IT, Bygg, Handel" />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Webbplats</label>
                <Input name="website" placeholder="https://exempel.se" />
              </div>

              <div className="col-span-2">
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Adress</label>
                <Input name="address" placeholder="Storgatan 1" />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Stad</label>
                <Input name="city" placeholder="Stockholm" />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Postnummer</label>
                <Input name="zip" placeholder="123 45" />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Land</label>
                <Input name="country" defaultValue="Sverige" />
              </div>

              <div>
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Telefon</label>
                <Input name="phone" placeholder="08-123 456 78" />
              </div>

              <div className="col-span-2">
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">E-post</label>
                <Input name="email" type="email" placeholder="info@exempel.se" />
              </div>

              <div className="col-span-2">
                <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-zinc-400 mb-1.5">Anteckningar</label>
                <Textarea name="notes" placeholder="Övrig information..." />
              </div>
            </div>

            <div className="flex items-center gap-3 pt-1">
              <Button type="submit" disabled={loading}>
                {loading ? 'Sparar…' : 'Skapa prospekt'}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => router.push('/prospects')}
              >
                Avbryt
              </Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}
