// svelte/src/lib/components/ui/input.svelte
<script lang="ts">
	interface Props {
		type?: string;
		class?: string;
		placeholder?: string;
		value?: string;
		disabled?: boolean;
		required?: boolean;
		id?: string;
		name?: string;
		step?: number | string;
		min?: number | string;
		max?: number | string;
	}

	let {
		type = "text",
		class: className = "",
		placeholder = "",
		value = $bindable(),
		disabled = false,
		required = false,
		id,
		name,
		step,
		min,
		max,
		...restProps
	}: Props = $props();
</script>

<input
	type={type}
	id={id}
	name={name}
	class="flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm ring-offset-white file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-gray-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 {className}"
	{placeholder}
	bind:value
	{disabled}
	{required}
	{step}
	{min}
	{max}
	{...restProps}
/>

// nextjs/src/components/ui/input.tsx
import { cn } from '@/lib/utils'
import { InputHTMLAttributes, forwardRef } from 'react'

const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(
  ({ className, ...props }, ref) => {
    return (
      <input
        ref={ref}
        className={cn(
          'flex h-10 w-full rounded-md border border-gray-200 bg-gray-50/50 px-3 py-2 text-sm text-gray-900 placeholder:text-gray-400 hover:bg-gray-50 focus:bg-white focus:border-zinc-500 focus:outline-none focus:ring-2 focus:ring-zinc-500/20 transition-all disabled:cursor-not-allowed disabled:opacity-50',
          className,
        )}
        {...props}
      />
    )
  },
)
Input.displayName = 'Input'

export { Input }
