// svelte/src/routes/(dashboard)/dashboard/contacts/[id]/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { invalidateAll } from "$app/navigation";
	import Card from "$lib/components/ui/card.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import Input from "$lib/components/ui/input.svelte";
	import Label from "$lib/components/ui/label.svelte";
	import { PencilIcon } from "heroicons-svelte/24/outline";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();

	let editing = $state(false);
	let formData = $state({
		firstName: "",
		lastName: "",
		email: "",
		phone: "",
		title: "",
		notes: "",
	});
	let error = $state("");

	$effect(() => {
		formData.firstName = data.contact.firstName;
		formData.lastName = data.contact.lastName;
		formData.email = data.contact.email ?? "";
		formData.phone = data.contact.phone ?? "";
		formData.title = data.contact.title ?? "";
		formData.notes = data.contact.notes ?? "";
	});
</script>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-3xl font-bold text-gray-900">
				{data.contact.firstName} {data.contact.lastName}
			</h1>
			<p class="mt-1 text-gray-600">{data.contact.company.name}</p>
		</div>
		<div class="flex gap-2">
			<Button onclick={() => (editing = !editing)}>
				<PencilIcon class="mr-2 h-5 w-5" />
				{editing ? "Avbryt" : "Redigera"}
			</Button>
			<a href="/dashboard/contacts">
				<Button variant="outline">Tillbaka till listan</Button>
			</a>
		</div>
	</div>

	<Card class="p-6 max-w-2xl">
		<h2 class="text-lg font-semibold text-gray-900 mb-4">Kontaktinformation</h2>
		{#if editing}
			<form
				method="POST"
				action="?/update"
				use:enhance={() => {
					return async ({ result, update }) => {
						await update();
						if (result.type === "success" && result.data?.success) {
							editing = false;
							await invalidateAll();
						} else if (result.type === "success" && result.data?.error) {
							error = result.data.error;
						}
					};
				}}
			>
				{#if error}
					<p class="mb-2 text-sm text-red-600">{error}</p>
				{/if}
				<div class="space-y-4">
					<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
						<div>
							<Label for="firstName">Förnamn</Label>
							<Input id="firstName" name="firstName" bind:value={formData.firstName} required />
						</div>
						<div>
							<Label for="lastName">Efternamn</Label>
							<Input id="lastName" name="lastName" bind:value={formData.lastName} required />
						</div>
					</div>
					<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
						<div>
							<Label for="email">E-post</Label>
							<Input id="email" name="email" type="email" bind:value={formData.email} />
						</div>
						<div>
							<Label for="phone">Telefon</Label>
							<Input id="phone" name="phone" bind:value={formData.phone} />
						</div>
					</div>
					<div>
						<Label for="title">Titel</Label>
						<Input id="title" name="title" bind:value={formData.title} />
					</div>
					<div>
						<Label for="notes">Anteckningar</Label>
						<textarea
							id="notes"
							name="notes"
							bind:value={formData.notes}
							rows="3"
							class="mt-1 block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
						></textarea>
					</div>
					<Button type="submit">Spara ändringar</Button>
				</div>
			</form>
		{:else}
			<dl class="space-y-3">
				<div>
					<dt class="text-sm font-medium text-gray-500">Företag</dt>
					<dd class="mt-1 text-gray-900">
						{#if data.contact.company.type === "CUSTOMER"}
							<a href="/dashboard/customers/{data.contact.company.id}" class="text-blue-600 hover:underline">
								{data.contact.company.name}
							</a>
						{:else}
							<a href="/dashboard/prospects/{data.contact.company.id}" class="text-blue-600 hover:underline">
								{data.contact.company.name}
							</a>
						{/if}
					</dd>
				</div>
				{#if data.contact.title}
					<div>
						<dt class="text-sm font-medium text-gray-500">Titel</dt>
						<dd class="mt-1 text-gray-900">{data.contact.title}</dd>
					</div>
				{/if}
				{#if data.contact.email}
					<div>
						<dt class="text-sm font-medium text-gray-500">E-post</dt>
						<dd class="mt-1 text-gray-900">
							<a href="mailto:{data.contact.email}" class="text-blue-600 hover:underline">{data.contact.email}</a>
						</dd>
					</div>
				{/if}
				{#if data.contact.phone}
					<div>
						<dt class="text-sm font-medium text-gray-500">Telefon</dt>
						<dd class="mt-1 text-gray-900">{data.contact.phone}</dd>
					</div>
				{/if}
				{#if data.contact.notes}
					<div>
						<dt class="text-sm font-medium text-gray-500">Anteckningar</dt>
						<dd class="mt-1 text-gray-900 whitespace-pre-wrap">{data.contact.notes}</dd>
					</div>
				{/if}
			</dl>
		{/if}
	</Card>
</div>

// nextjs/src/app/(dashboard)/contacts/[id]/page.tsx
import { prisma } from '@/lib/db'
import { formatDate } from '@/lib/utils'
import { EditContactButton } from '@/app/(dashboard)/customers/[id]/KundEditActions'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { BackButton } from '@/components/ui/back-button'

interface PageProps {
  params: Promise<{ id: string }>
}

export default async function KontaktDetailPage({ params }: PageProps) {
  const { id } = await params

  const contact = await prisma.contact.findUnique({
    where: { id },
    include: {
      customer: true,
      activities: {
        include: { user: true },
        orderBy: { createdAt: 'desc' },
        take: 20,
      },
    },
  })

  if (!contact) notFound()

  const customerHref = `/customers/${contact.customerId}`

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div>
        <BackButton href="/contacts" label="Kontakter" />
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-zinc-100">
              {contact.firstName} {contact.lastName}
            </h1>
            {contact.title && <p className="text-sm text-gray-500 mt-0.5">{contact.title}</p>}
          </div>
          <EditContactButton contact={{
            id: contact.id,
            firstName: contact.firstName,
            lastName: contact.lastName,
            email: contact.email,
            phone: contact.phone,
            title: contact.title,
            role: contact.role,
            notes: contact.notes,
          }} />
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <div className="panel-surface">
          <div className="px-6 py-4 border-b border-gray-100">
            <h2 className="text-sm font-semibold text-gray-900">Kontaktuppgifter</h2>
          </div>
          <div className="p-6 space-y-3">
            {[
              {
                label: 'Företag',
                value: (
                  <Link href={customerHref} className="font-medium text-gray-900 hover:text-zinc-600 transition-colors">
                    {contact.customer.name}
                  </Link>
                ),
              },
              { label: 'Titel', value: contact.title ?? '–' },
              { label: 'E-post', value: contact.email ?? '–' },
              { label: 'Telefon', value: contact.phone ?? '–' },
              { label: 'Skapad', value: formatDate(contact.createdAt) },
            ].map(({ label, value }) => (
              <div key={label} className="flex justify-between text-sm">
                <span className="text-gray-500">{label}</span>
                <span className="text-gray-900 font-medium">{value}</span>
              </div>
            ))}
          </div>
        </div>

        {contact.notes && (
          <div className="panel-surface">
            <div className="px-6 py-4 border-b border-gray-100">
              <h2 className="text-sm font-semibold text-gray-900">Anteckningar</h2>
            </div>
            <div className="p-6">
              <p className="text-sm text-gray-700 whitespace-pre-wrap">{contact.notes}</p>
            </div>
          </div>
        )}
      </div>

      {contact.activities.length > 0 && (
        <div className="panel-surface">
          <div className="px-6 py-4 border-b border-gray-100">
            <h2 className="text-sm font-semibold text-gray-900">Aktivitet</h2>
          </div>
          <div className="p-6">
            <div className="space-y-4">
              {contact.activities.map((a) => (
                <div key={a.id} className="flex items-start gap-3">
                  <div className="h-8 w-8 rounded-full bg-zinc-100 flex items-center justify-center shrink-0">
                    <span className="text-xs font-semibold text-zinc-700">
                      {a.user?.name?.charAt(0) ?? 'S'}
                    </span>
                  </div>
                  <div>
                    <p className="text-sm text-gray-700">
                      <span className="font-medium">{a.user?.name ?? 'System'}</span>{' '}
                      {a.title}
                    </p>
                    <p className="text-xs text-gray-400 mt-0.5">{formatDate(a.createdAt)}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
