// nextjs/src/components/layout/sidebar.tsx
'use client'

import Link from 'next/link'
import Image from 'next/image'
import { usePathname } from 'next/navigation'
import { cn } from '@/lib/utils'
import { DEFAULT_AVATAR_URL } from '@/lib/avatar'
import { motion } from 'framer-motion'
import {
  LayoutDashboard,
  Building2,
  Users,
  FileText,
  ClipboardList,
  Banknote,
  Box,
  CheckSquare,
  Calendar,
  CalendarDays,
  LifeBuoy,
  BookOpen,
  BarChart3,
  Settings,
  Filter,
  ScrollText,
  UserCircle2,
  UsersRound,
} from 'lucide-react'

const navGroups = [
  {
    label: 'Huvud',
    items: [
      { href: '/dashboard', label: 'Översikt', icon: LayoutDashboard },
    ],
  },
  {
    label: 'CRM',
    items: [
      { href: '/customers', label: 'Kunder', icon: Building2 },
      { href: '/prospects', label: 'Prospekts', icon: Filter },
      { href: '/contacts', label: 'Kontakter', icon: UserCircle2 },
      { href: '/pipelines', label: 'Bolagsfakta Pipeline', icon: Users },
    ],
  },
  {
    label: 'Affär',
    items: [
      { href: '/quotes', label: 'Offerter', icon: FileText },
      { href: '/contracts', label: 'Avtal', icon: ClipboardList },
      { href: '/invoices', label: 'Fakturor', icon: Banknote },
      { href: '/projects', label: 'Projekt', icon: Box },
    ],
  },
  {
    label: 'Arbete',
    items: [
      { href: '/tasks', label: 'Uppgifter', icon: CheckSquare },
      { href: '/meetings', label: 'Möten', icon: Calendar },
      { href: '/calendar', label: 'Kalender', icon: CalendarDays },
      { href: '/support', label: 'Support', icon: LifeBuoy },
    ],
  },
  {
    label: 'System',
    items: [
      { href: '/reports', label: 'Rapporter', icon: BarChart3 },
      { href: '/knowledge-base', label: 'Kunskapsbas', icon: BookOpen },
      { href: '/system-logs', label: 'Systemloggar', icon: ScrollText },
      { href: '/settings', label: 'Inställningar', icon: Settings },
      { href: '/users', label: 'Användare', icon: UsersRound },
    ],
  },
]

export function Sidebar({ onClose }: { onClose?: () => void }) {
  const pathname = usePathname()

  return (
    <div className="flex h-full flex-col bg-white dark:bg-zinc-900 border-r border-gray-200 dark:border-zinc-800">
      {/* Logo */}
      <div className="flex h-14 shrink-0 items-center px-5 border-b border-gray-200 dark:border-zinc-800">
        <Link
          href="/dashboard"
          onClick={onClose}
          className="flex items-center gap-2.5 min-w-0"
        >
          <Image
            src={DEFAULT_AVATAR_URL}
            alt="BCRM"
            width={32}
            height={32}
            className="h-8 w-8 rounded-lg object-cover shrink-0"
          />
          <span className="text-[15px] font-bold text-gray-900 dark:text-white tracking-tight truncate">
            BCRM
          </span>
        </Link>
      </div>

      {/* Nav */}
      <nav className="flex-1 overflow-y-auto no-scrollbar py-4 px-3 space-y-5">
        {navGroups.map((group) => (
          <div key={group.label}>
            <p className="px-3 mb-1 text-[10px] font-semibold uppercase tracking-widest text-gray-400 dark:text-zinc-600">
              {group.label}
            </p>
            <div className="space-y-0.5">
              {group.items.map(({ href, label, icon: Icon }) => {
                const active = pathname === href || pathname.startsWith(href + '/')
                return (
                  <Link
                    key={href}
                    href={href}
                    onClick={onClose}
                    className={cn(
                      "relative flex items-center gap-2.5 rounded-md px-3 py-2 text-[13px] font-normal transition-colors",
                      active
                        ? "bg-gray-100 text-gray-900 dark:bg-zinc-800 dark:text-white font-medium"
                        : "text-gray-500 hover:bg-gray-50 hover:text-gray-900 dark:text-zinc-500 dark:hover:bg-zinc-800/60 dark:hover:text-zinc-200",
                    )}
                  >
                    {active && (
                      <motion.div
                        layoutId="sidebar-active"
                        className="absolute inset-0 rounded-md bg-gray-100 dark:bg-zinc-800"
                        transition={{ type: 'spring', stiffness: 400, damping: 35 }}
                      />
                    )}
                    <Icon className={cn('relative h-4 w-4 shrink-0', active ? 'text-gray-700 dark:text-zinc-300' : 'text-gray-400 dark:text-zinc-600')} />
                    <span className="relative">{label}</span>
                  </Link>
                )
              })}
            </div>
          </div>
        ))}
      </nav>
    </div>
  )
}

// svelte/src/lib/components/layout/sidebar.svelte
<script lang="ts">
	import { page } from "$app/stores";
	import {
		HomeIcon,
		UserGroupIcon,
		BuildingOfficeIcon,
		DocumentTextIcon,
		CurrencyDollarIcon,
		ClipboardDocumentListIcon,
		ClockIcon,
		CalendarIcon,
		InboxIcon,
		ChartBarIcon,
		Cog6ToothIcon,
		DocumentMagnifyingGlassIcon,
		BoltIcon,
	} from "heroicons-svelte/24/outline";

	interface Props {
		user?: { name: string; email: string; role: string };
	}

	let { user }: Props = $props();

	interface NavItem {
		label: string;
		href: string;
		icon: any;
	}

	const baseNavItems: NavItem[] = [
		{ label: "Instrumentpanel", href: "/dashboard", icon: HomeIcon },
		{ label: "Pipelines", href: "/dashboard/pipelines", icon: BoltIcon },
		{ label: "Prospekt", href: "/dashboard/prospects", icon: UserGroupIcon },
		{ label: "Kunder", href: "/dashboard/customers", icon: BuildingOfficeIcon },
		{ label: "Kontakter", href: "/dashboard/contacts", icon: UserGroupIcon },
		{ label: "Offerter", href: "/dashboard/quotes", icon: DocumentTextIcon },
		{ label: "Avtal", href: "/dashboard/contracts", icon: DocumentTextIcon },
		{ label: "Fakturor", href: "/dashboard/invoices", icon: CurrencyDollarIcon },
		{ label: "Uppgifter", href: "/dashboard/tasks", icon: ClipboardDocumentListIcon },
		{ label: "Tidrapportering", href: "/dashboard/time-tracking", icon: ClockIcon },
		{ label: "Möten", href: "/dashboard/meetings", icon: CalendarIcon },
		{ label: "Support", href: "/dashboard/support", icon: InboxIcon },
		{ label: "Rapporter", href: "/dashboard/reports", icon: ChartBarIcon },
		{ label: "Systemloggar", href: "/dashboard/systemloggar", icon: DocumentMagnifyingGlassIcon },
		{ label: "Inställningar", href: "/dashboard/settings", icon: Cog6ToothIcon },
	];

	const navItems = $derived(
		user?.role === "ADMIN"
			? baseNavItems
			: baseNavItems.filter((item) => item.href !== "/dashboard/systemloggar"),
	);
	
	let collapsed = $state(false);
</script>

<aside class="flex h-screen flex-col border-r border-gray-200 bg-white">
	<div class="flex h-16 items-center border-b border-gray-200 px-4">
		<h1 class="text-xl font-bold text-gray-900">ProSC</h1>
	</div>
	
	<nav class="flex-1 space-y-1 overflow-y-auto px-3 py-4">
		{#each navItems as item}
			{@const Icon = item.icon}
			<a
				href={item.href}
				class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 {$page?.url?.pathname === item.href ? 'bg-blue-50 text-blue-700' : 'text-gray-700'}"
			>
				<Icon class="h-5 w-5" />
				<span>{item.label}</span>
			</a>
		{/each}
	</nav>
</aside>
