// nextjs/src/components/layout/topbar.tsx
'use client'

import { signOut, useSession } from 'next-auth/react'
import { Bars3Icon } from '@heroicons/react/24/outline'

interface TopbarProps {
  onMenuClick: () => void
}

export function Topbar({ onMenuClick }: TopbarProps) {
  const { data: session } = useSession()

  const initials = session?.user?.name
    ? session.user.name.split(' ').map((n) => n[0]).slice(0, 2).join('').toUpperCase()
    : '?'

  return (
    <header className="flex h-14 shrink-0 items-center justify-between border-b border-gray-200 bg-white px-4 lg:px-6">
      <button
        onClick={onMenuClick}
        className="rounded-md p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600 transition-colors lg:hidden"
        aria-label="Öppna meny"
      >
        <Bars3Icon className="h-5 w-5" />
      </button>

      <div className="flex items-center gap-3 ml-auto">
        <div className="text-right hidden sm:block">
          <p className="text-sm font-medium text-gray-900 leading-tight">{session?.user?.name}</p>
          <p className="text-xs text-gray-500">{session?.user?.role}</p>
        </div>
        <button
          onClick={() => signOut({ callbackUrl: '/login' })}
          title="Logga ut"
          className="h-8 w-8 rounded-full bg-zinc-800 text-white text-[11px] font-semibold flex items-center justify-center hover:bg-zinc-700 transition-colors shrink-0"
        >
          {initials}
        </button>
      </div>
    </header>
  )
}

// svelte/src/lib/components/layout/topbar.svelte
<script lang="ts">
	import { Bars3Icon, BellIcon, MagnifyingGlassIcon } from "heroicons-svelte/24/outline";

	interface Props {
		user?: {
			name: string;
			email: string;
		};
		ontogglemenu?: () => void;
	}

	let { user, ontogglemenu }: Props = $props();
</script>

<header class="flex h-16 items-center justify-between border-b border-gray-200 bg-white px-3 sm:px-6">
	<div class="flex flex-1 items-center gap-2 sm:gap-4">
		<button
			type="button"
			onclick={ontogglemenu}
			class="rounded-lg p-2 text-gray-600 hover:bg-gray-100 lg:hidden"
		>
			<Bars3Icon class="h-6 w-6" />
		</button>
		<div class="relative hidden flex-1 sm:block sm:max-w-md">
			<MagnifyingGlassIcon class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />
			<input
				type="text"
				placeholder="Sök..."
				class="w-full rounded-lg border border-gray-300 bg-white py-2 pl-10 pr-4 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
			/>
		</div>
	</div>

	<div class="flex items-center gap-2 sm:gap-4">
		<button class="relative rounded-lg p-2 text-gray-600 hover:bg-gray-100">
			<BellIcon class="h-5 w-5" />
			<span class="absolute right-1 top-1 h-2 w-2 rounded-full bg-red-500"></span>
		</button>

		<div class="flex items-center gap-3">
			<div class="h-8 w-8 rounded-full bg-blue-600 flex items-center justify-center text-white font-medium">
				{user?.name?.[0]?.toUpperCase() || "U"}
			</div>
			<div class="hidden md:block">
				<p class="text-sm font-medium text-gray-900">{user?.name || "Användare"}</p>
				<p class="text-xs text-gray-500">{user?.email || ""}</p>
			</div>
			<form method="POST" action="/logout">
				<button
					type="submit"
					class="ml-2 rounded-md px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100"
				>
					Logga ut
				</button>
			</form>
		</div>
	</div>
</header>
