// nextjs/src/components/ui/button.tsx
import { cn } from '@/lib/utils'
import { ButtonHTMLAttributes, forwardRef } from 'react'

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'outline' | 'ghost' | 'destructive' | 'link'
  size?: 'sm' | 'md' | 'lg'
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = 'default', size = 'md', ...props }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          'inline-flex items-center justify-center gap-2 rounded-md font-medium transition-colors focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50',
          {
            'bg-zinc-800 text-white hover:bg-zinc-900': variant === 'default',
            'border border-gray-200 bg-white text-gray-700 hover:bg-gray-50 hover:text-gray-900': variant === 'outline',
            'text-gray-600 hover:bg-gray-100 hover:text-gray-900': variant === 'ghost',
            'bg-red-600 text-white hover:bg-red-700': variant === 'destructive',
            'text-zinc-700 underline-offset-4 hover:underline': variant === 'link',
            'h-8 px-3 text-sm': size === 'sm',
            'h-10 px-4 text-sm': size === 'md',
            'h-11 px-5 text-sm': size === 'lg',
          },
          className,
        )}
        {...props}
      />
    )
  },
)
Button.displayName = 'Button'

export { Button }

// svelte/src/lib/components/ui/button.svelte
<script lang="ts">
	import { Button } from "bits-ui";
	import type { Snippet } from "svelte";

	interface Props {
		variant?: "default" | "outline" | "ghost" | "destructive";
		size?: "sm" | "md" | "lg";
		class?: string;
		children?: Snippet;
	}

	let { variant = "default", size = "md", class: className = "", children, ...restProps }: Props & Record<string, unknown> = $props();

	const variantClasses = {
		default: "bg-blue-600 text-white hover:bg-blue-700",
		outline: "border border-gray-300 bg-white hover:bg-gray-50",
		ghost: "hover:bg-gray-100",
		destructive: "bg-red-600 text-white hover:bg-red-700",
	};

	const sizeClasses = {
		sm: "px-3 py-1.5 text-sm",
		md: "px-4 py-2 text-base",
		lg: "px-6 py-3 text-lg",
	};
</script>

<Button.Root
	class="inline-flex items-center justify-center rounded-md font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none {variantClasses[variant]} {sizeClasses[size]} {className}"
	{...restProps}
>
	{#if children}
		{@render children()}
	{/if}
</Button.Root>
