// nextjs/src/app/(dashboard)/contacts/[id]/page.tsx
import { prisma } from '@/lib/db'
import { formatDate } from '@/lib/utils'
import { EditContactButton } from '@/app/(dashboard)/customers/[id]/KundEditActions'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { BackButton } from '@/components/ui/back-button'

interface PageProps {
  params: Promise<{ id: string }>
}

export default async function KontaktDetailPage({ params }: PageProps) {
  const { id } = await params

  const contact = await prisma.contact.findUnique({
    where: { id },
    include: {
      customer: true,
      activities: {
        include: { user: true },
        orderBy: { createdAt: 'desc' },
        take: 20,
      },
    },
  })

  if (!contact) notFound()

  const customerHref = `/customers/${contact.customerId}`

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div>
        <BackButton href="/contacts" label="Kontakter" />
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-zinc-100">
              {contact.firstName} {contact.lastName}
            </h1>
            {contact.title && <p className="text-sm text-gray-500 mt-0.5">{contact.title}</p>}
          </div>
          <EditContactButton contact={{
            id: contact.id,
            firstName: contact.firstName,
            lastName: contact.lastName,
            email: contact.email,
            phone: contact.phone,
            title: contact.title,
            role: contact.role,
            notes: contact.notes,
          }} />
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <div className="panel-surface">
          <div className="px-6 py-4 border-b border-gray-100">
            <h2 className="text-sm font-semibold text-gray-900">Kontaktuppgifter</h2>
          </div>
          <div className="p-6 space-y-3">
            {[
              {
                label: 'Företag',
                value: (
                  <Link href={customerHref} className="font-medium text-gray-900 hover:text-zinc-600 transition-colors">
                    {contact.customer.name}
                  </Link>
                ),
              },
              { label: 'Titel', value: contact.title ?? '–' },
              { label: 'E-post', value: contact.email ?? '–' },
              { label: 'Telefon', value: contact.phone ?? '–' },
              { label: 'Skapad', value: formatDate(contact.createdAt) },
            ].map(({ label, value }) => (
              <div key={label} className="flex justify-between text-sm">
                <span className="text-gray-500">{label}</span>
                <span className="text-gray-900 font-medium">{value}</span>
              </div>
            ))}
          </div>
        </div>

        {contact.notes && (
          <div className="panel-surface">
            <div className="px-6 py-4 border-b border-gray-100">
              <h2 className="text-sm font-semibold text-gray-900">Anteckningar</h2>
            </div>
            <div className="p-6">
              <p className="text-sm text-gray-700 whitespace-pre-wrap">{contact.notes}</p>
            </div>
          </div>
        )}
      </div>

      {contact.activities.length > 0 && (
        <div className="panel-surface">
          <div className="px-6 py-4 border-b border-gray-100">
            <h2 className="text-sm font-semibold text-gray-900">Aktivitet</h2>
          </div>
          <div className="p-6">
            <div className="space-y-4">
              {contact.activities.map((a) => (
                <div key={a.id} className="flex items-start gap-3">
                  <div className="h-8 w-8 rounded-full bg-zinc-100 flex items-center justify-center shrink-0">
                    <span className="text-xs font-semibold text-zinc-700">
                      {a.user?.name?.charAt(0) ?? 'S'}
                    </span>
                  </div>
                  <div>
                    <p className="text-sm text-gray-700">
                      <span className="font-medium">{a.user?.name ?? 'System'}</span>{' '}
                      {a.title}
                    </p>
                    <p className="text-xs text-gray-400 mt-0.5">{formatDate(a.createdAt)}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// svelte/src/routes/(dashboard)/dashboard/customers/[id]/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { invalidateAll } from "$app/navigation";
	import Card from "$lib/components/ui/card.svelte";
	import Button from "$lib/components/ui/button.svelte";
	import Input from "$lib/components/ui/input.svelte";
	import Label from "$lib/components/ui/label.svelte";
	import { format } from "date-fns";
	import { sv } from "date-fns/locale";
	import { PencilIcon } from "heroicons-svelte/24/outline";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();

	let editing = $state(false);
	let formData = $state({
		name: "",
		email: "",
		phone: "",
		industry: "",
		website: "",
	});
	let error = $state("");

	$effect(() => {
		formData.name = data.company.name;
		formData.email = data.company.email ?? "";
		formData.phone = data.company.phone ?? "";
		formData.industry = data.company.industry ?? "";
		formData.website = data.company.website ?? "";
	});
</script>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-3xl font-bold text-gray-900">{data.company.name}</h1>
			<span class="mt-2 inline-flex rounded-full bg-green-100 px-3 py-1 text-sm font-medium text-green-800">Kund</span>
		</div>
		<div class="flex gap-2">
			<a href="/dashboard/customers/{data.company.id}/systembehov">
				<Button variant="outline">Systembehov</Button>
			</a>
			<Button onclick={() => (editing = !editing)}>
				<PencilIcon class="mr-2 h-5 w-5" />
				{editing ? "Avbryt" : "Redigera"}
			</Button>
			<a href="/dashboard/customers">
				<Button variant="outline">Tillbaka till listan</Button>
			</a>
		</div>
	</div>

	<div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
		<div class="lg:col-span-2 space-y-6">
			<Card class="p-6">
				<h2 class="text-lg font-semibold text-gray-900 mb-4">Företagsinformation</h2>
				{#if editing}
					<form
						method="POST"
						action="?/update"
						use:enhance={() => {
							return async ({ result, update }) => {
								await update();
								if (result.type === "success" && result.data?.success) {
									editing = false;
									await invalidateAll();
								} else if (result.type === "success" && result.data?.error) {
									error = result.data.error;
								}
							};
						}}
					>
						{#if error}
							<p class="mb-2 text-sm text-red-600">{error}</p>
						{/if}
						<div class="space-y-4">
							<div>
								<Label for="name">Företagsnamn</Label>
								<Input id="name" name="name" bind:value={formData.name} required />
							</div>
							<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
								<div>
									<Label for="email">E-post</Label>
									<Input id="email" name="email" type="email" bind:value={formData.email} />
								</div>
								<div>
									<Label for="phone">Telefon</Label>
									<Input id="phone" name="phone" bind:value={formData.phone} />
								</div>
							</div>
							<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
								<div>
									<Label for="industry">Bransch</Label>
									<Input id="industry" name="industry" bind:value={formData.industry} />
								</div>
								<div>
									<Label for="website">Webbplats</Label>
									<Input id="website" name="website" bind:value={formData.website} />
								</div>
							</div>
							<div class="flex gap-4">
								<Button type="submit">Spara ändringar</Button>
								<Button variant="outline" type="button" onclick={() => (editing = false)}>Avbryt</Button>
							</div>
						</div>
					</form>
				{:else}
					<dl class="space-y-4">
						<div>
							<dt class="text-sm font-medium text-gray-500">E-post</dt>
							<dd class="mt-1 text-sm text-gray-900">{data.company.email || "—"}</dd>
						</div>
						<div>
							<dt class="text-sm font-medium text-gray-500">Telefon</dt>
							<dd class="mt-1 text-sm text-gray-900">{data.company.phone || "—"}</dd>
						</div>
						<div>
							<dt class="text-sm font-medium text-gray-500">Bransch</dt>
							<dd class="mt-1 text-sm text-gray-900">{data.company.industry || "—"}</dd>
						</div>
						<div>
							<dt class="text-sm font-medium text-gray-500">Webbplats</dt>
							<dd class="mt-1 text-sm text-gray-900">
								{#if data.company.website}
									<a href={data.company.website} target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-700">
										{data.company.website}
									</a>
								{:else}
									—
								{/if}
							</dd>
						</div>
					</dl>
				{/if}
			</Card>

			<Card class="p-6">
				<h2 class="text-lg font-semibold text-gray-900 mb-4">Senaste aktivitet</h2>
				<div class="space-y-4">
					{#if data.company.activities.length === 0}
						<p class="text-sm text-gray-500">Ingen aktivitet än</p>
					{:else}
						{#each data.company.activities as activity}
							<div class="border-l-2 border-gray-200 pl-4">
								<p class="text-sm font-medium text-gray-900">{activity.title}</p>
								{#if activity.description}
									<p class="text-sm text-gray-600">{activity.description}</p>
								{/if}
								<p class="mt-1 text-xs text-gray-500">
									{activity.user?.name || "System"} • {format(new Date(activity.createdAt), "d MMM yyyy HH:mm", { locale: sv })}
								</p>
							</div>
						{/each}
					{/if}
				</div>
			</Card>
		</div>

		<div class="space-y-6">
			<Card class="p-6">
				<h2 class="text-lg font-semibold text-gray-900 mb-4">Snabbstatistik</h2>
				<dl class="space-y-3">
					<div>
						<dt class="text-sm text-gray-500">Kontakter</dt>
						<dd class="text-2xl font-bold text-gray-900">{data.company.contacts.length}</dd>
					</div>
					<div>
						<dt class="text-sm text-gray-500">Projekt</dt>
						<dd class="text-2xl font-bold text-gray-900">{data.company.projects.length}</dd>
					</div>
					<div>
						<dt class="text-sm text-gray-500">Offerter</dt>
						<dd class="text-2xl font-bold text-gray-900">{data.company.quotes.length}</dd>
					</div>
					<div>
						<dt class="text-sm text-gray-500">Avtal</dt>
						<dd class="text-2xl font-bold text-gray-900">{data.company.contracts.length}</dd>
					</div>
				</dl>
			</Card>

			{#if data.company.contacts.length > 0}
				<Card class="p-6">
					<h2 class="text-lg font-semibold text-gray-900 mb-4">Kontakter</h2>
					<ul class="space-y-2">
						{#each data.company.contacts as contact}
							<li>
								<a
									href="/dashboard/contacts/{contact.id}"
									class="text-blue-600 hover:underline"
								>
									{contact.firstName} {contact.lastName}
								</a>
							</li>
						{/each}
					</ul>
				</Card>
			{/if}

			{#if data.company.quotes.length > 0}
				<Card class="p-6">
					<h2 class="text-lg font-semibold text-gray-900 mb-4">Offerter</h2>
					<ul class="space-y-2">
						{#each data.company.quotes as quote}
							<li>
								<a href="/dashboard/quotes/{quote.id}" class="text-blue-600 hover:underline">
									{quote.number} – {quote.title}
								</a>
								<span class="text-sm text-gray-500">({quote.total.toFixed(0)} kr)</span>
							</li>
						{/each}
					</ul>
				</Card>
			{/if}
		</div>
	</div>
</div>
