// nextjs/src/app/(dashboard)/projects/new/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ChevronRight } from 'lucide-react'
import { toast } from '@/lib/toast'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Select } from '@/components/ui/select'

export default function NyProjektPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setLoading(true)

    const form = e.currentTarget
    const data = Object.fromEntries(new FormData(form))

    try {
      const res = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      })

      if (!res.ok) throw new Error('Kunde inte skapa projekt')
      toast.success('Projekt skapat')
      router.push('/projects')
    } catch {
      toast.error('Ett fel uppstod. Försök igen.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <nav className="flex items-center gap-1.5 text-xs text-gray-400 mb-2">
          <Link href="/projects" className="hover:text-gray-600 transition-colors">Projekt</Link>
          <ChevronRight className="h-3 w-3" />
          <span className="text-gray-600">Nytt projekt</span>
        </nav>
        <h1 className="text-2xl font-bold text-gray-900">Nytt projekt</h1>
        <p className="text-sm text-gray-500 mt-1">Fyll i uppgifterna nedan</p>
      </div>

      <div className="panel-surface">
        <div className="px-6 py-4 border-b border-gray-100">
          <h2 className="text-sm font-semibold text-gray-900">Projektuppgifter</h2>
        </div>
        <div className="p-6 space-y-4">
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 mb-1.5">
                Namn <span className="text-red-500">*</span>
              </label>
              <Input name="name" required placeholder="T.ex. BCRM Enterprise" />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 mb-1.5">Beskrivning</label>
              <Textarea
                name="description"
                placeholder="Beskriv projektet..."
                rows={4}
              />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wide text-gray-500 mb-1.5">Status</label>
              <Select name="status" defaultValue="ACTIVE">
                <option value="ACTIVE">Aktiv</option>
                <option value="PAUSED">Pausad</option>
                <option value="ARCHIVED">Arkiverad</option>
              </Select>
            </div>

            <div className="flex items-center gap-3 pt-1">
              <Button type="submit" disabled={loading}>
                {loading ? 'Sparar…' : 'Skapa projekt'}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => router.push('/projects')}
              >
                Avbryt
              </Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}

// svelte/src/routes/(dashboard)/dashboard/products/new/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { goto } from "$app/navigation";
	import Button from "$lib/components/ui/button.svelte";
	import Input from "$lib/components/ui/input.svelte";
	import Label from "$lib/components/ui/label.svelte";
	import Card from "$lib/components/ui/card.svelte";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();

	let loading = $state(false);
	let error = $state("");
</script>

<div class="mx-auto max-w-2xl space-y-6">
	<div>
		<h1 class="text-3xl font-bold text-gray-900">Ny produkt</h1>
		<p class="mt-1 text-gray-500">Skapa en ny produkt kopplad till en kund</p>
	</div>

	<Card class="p-6">
		{#if error}
			<div class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>
		{/if}

		<form
			method="POST"
			action="?/create"
			use:enhance={() => {
				loading = true;
				error = "";
				return async ({ result, update }) => {
					loading = false;
					if (result.type === "failure") {
						error = (result.data as { error?: string })?.error || "Något gick fel";
					} else if (result.type === "redirect") {
						goto(result.location);
					} else {
						await update();
					}
				};
			}}
			class="space-y-4"
		>
			<div>
				<Label for="companyId">Kund *</Label>
				<select
					id="companyId"
					name="companyId"
					required
					class="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
				>
					<option value="">Välj kund...</option>
					{#each data.customers as customer}
						<option value={customer.id}>{customer.name}</option>
					{/each}
				</select>
			</div>

			<div>
				<Label for="name">Produktnamn *</Label>
				<Input id="name" name="name" required placeholder="T.ex. Webbshop, Mobilapp..." />
			</div>

			<div>
				<Label for="description">Beskrivning</Label>
				<textarea
					id="description"
					name="description"
					rows="3"
					placeholder="Beskriv produkten..."
					class="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
				></textarea>
			</div>

			<div class="flex items-center gap-3 pt-2">
				<Button type="submit" disabled={loading}>
					{loading ? "Skapar..." : "Skapa produkt"}
				</Button>
				<a href="/dashboard/products">
					<Button variant="outline">Avbryt</Button>
				</a>
			</div>
		</form>
	</Card>
</div>
